name: vitaltracer_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  settings_ui: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/VTlogo.png
    - lib/images/ecg.png
    - lib/images/google.png
    - lib/images/heart.png
    - lib/images/vt.png
    - lib/images/vt1.png
    - lib/images/temp.jpg
    - lib/images/ECGData.png


